apiVersion: v1
kind: ConfigMap
metadata:
  name: sports-api-config
data:
  CLOUD_SQL_CONNECTION_NAME: sports-tournaments-multicloud:us-central1:sports-mysql
  DB_USER: sports_user
  DB_NAME: sports_db
  OBJECT_STORAGE_API_URL: http://object-storage:3000
  HOTEL_API_URL: http://157.137.215.20
  CINE_API_URL: http://4.255.124.181
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
