apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sports-api-secrets-gke
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/sports-tournaments-multicloud/secrets/sports-db-password/versions/latest"
        path: "db-password"
