apiVersion: v1
kind: ConfigMap
metadata:
  name: object-storage-config
  namespace: default
data:
  GCS_BUCKET_NAME: sports-tournaments-artifacts
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
