apiVersion: v1
kind: ServiceAccount
metadata:
  name: object-storage-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: object-storage-gsa@sports-tournaments-multicloud.iam.gserviceaccount.com
